### ISSUE TITLE
Image Tag doesn't reflect proper SKLearn Version

### ISSUE THREAD

**Issue by jperuggia** [aws/sagemaker-scikit-learn-container#115]
When pulling the latest supported image with the tag of `683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:1.0-1-cpu-py3` and mounting locally to see what packages are there we get via `docker run -it --entrypoint /bin/sh 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:1.0-1-cpu-py3` and then running the command of `pip list` we can see the following output: 

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1916227/170512476-a98359bb-41bb-4f93-a737-556efcee0908.png">

**Comment by jperuggia** [comment]
> 

I see, the image tags should then be {major}.{minor}-{iteration} instead of the typical semantic version tags that sklearn is using.  If this is true, this issue can be closed without any further action needed.

**Comment by mabunday** [comment]
@lorenzwalthert is correct here but I agree the versioning is confusing and not ideal. I'm going to close this, but I'll see if we can make the scheme clearer in the documentation.
