### ISSUE TITLE
How to solve the problem of ValueError: Expected 2D array, got 1D array instead

### ISSUE THREAD

**Issue by yyuankm** [aws/sagemaker-scikit-learn-container#15]
I refer to the same process to deploy the sagemaker endpoint for my own application. I can predict the results in Jupyter Notebook by using 1d array. Then, I would like invoke it in postman. It complains "ValueError: Expected 2D array, got 1D array instead". 

The Content-Type is set as 'text/csv'. The body just contains the data stream. 

I never met such trouble for the sagemaker built-in algorithm. 

Any comments are welcome!

**Comment by ericaws** [comment]
The data is expected to be any number of prediction rows. This should be solveable by wrapping in an array, or appending '\n' at end if string.

Can you provide the input_fn and the inference call you are making?

**Comment by zlufy90** [comment]
Hello, I have the same issue.
This data works: payload = "5.1,3.5,1.4,0.2\n6.3,3.3,6.0,2.5"
But this does not work: payload = "5.1,3.5,1.4,0.2"
This also does not work: payload = "5.1,3.5,1.4,0.2\n"

Could any one please tell me how to solve it.

My full code is 
```
import boto3
endpoint_name= 'sagemaker-scikit-learn-2021-04-21-05-58-59-418'
client = boto3.client('runtime.sagemaker')

# payload = "5.1,3.5,1.4,0.2\n6.3,3.3,6.0,2.5" # this works
payload = "5.1,3.5,1.4,0.2\n" # this does not work

result = client.invoke_endpoint(
    EndpointName=endpoint_name,
    Body=payload,
    ContentType='text/csv')

print(result['Body'].read().decode())

```

**Comment by presich** [comment]
> The data is expected to be any number of prediction rows. This should be solveable by wrapping in an array, or appending '\n' at end if string.

Hi,
this didn't help. We haveing the same error as in the post above.
