### ISSUE TITLE
Joblib unable to find custom transformer in gunicorn env

### ISSUE THREAD

**Issue by WouterJTB** [aws/sagemaker-scikit-learn-container#157]
My issue is similar to this one, but none of the proposed solutions seem to be working [Custom TransformerMixin #725](https://github.com/aws/amazon-sagemaker-examples/issues/725)

I'm running a batchtransform step inside a pipeline started from a notebook in sagemaker studio

Model definition:

```
model = SKLearnModel(
    name=model_name,
    model_data=model_data_S3_URI,
    entry_point="inference.py",
    dependencies=["utils.py"],
    source_dir="s3://bucket/sourcedir.tar.gz", #contains inference.py and utils.py
    code_location=code_location,
    role=role,
    sagemaker_session=pipeline_session,
    framework_version="1.0-1",
    py_version="py3",
)
```

inference.py
```
from __future__ import print_function
from utils import CustomImputer

from io import StringIO
import os
import logging
import pandas as pd
import joblib

...

def model_fn(model_dir):
    model = joblib.load(os.path.join(model_dir, "model.joblib"))
    return model
```

utils.py
```
from sklearn.impute import SimpleImputer

class CustomImputer(SimpleImputer):
    def get_feature_names_out(self, _=None):
        return self.feature_names_in_.tolist()
```

Error log:

> sagemaker_containers._errors.ClientError: Can't get attribute 'CustomImputer' on <module '__main__' from '/miniconda3/bin/gunicorn'>

> Traceback (most recent call last): File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_functions.py", line 93, in wrapper return fn(*args, **kwargs) File "/opt/ml/code/inference.py", line 61, in model_fn model = joblib.load(os.path.join(model_dir, "model.joblib")) File "/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 658, in load obj = _unpickle(fobj, filename, mmap_mode) File "/miniconda3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle obj = unpickler.load() File "/miniconda3/lib/python3.7/pickle.py", line 1088, in load dispatch[key[0]](self) File "/miniconda3/lib/python3.7/pickle.py", line 1385, in load_stack_global self.append(self.find_class(module, name)) File "/miniconda3/lib/python3.7/pickle.py", line 1428, in find_class return _getattribute(sys.modules[module], name)[0] File "/miniconda3/lib/python3.7/pickle.py", line 299, in _getattribute .format(name, obj)) from None

Some things I tried

- Moving the import of CustomImputer to inside model_fn
- Defining the CustomImputer inside the inference.py script
- Defining the CustomImputer inside model_fn

**Comment by lorenzwalthert** [comment]
I had at some point the same problem which I don't recall in detail but I had a local `source_dir`, a folder instead of a file in `dependencies` and an `__init__.py` in dependencies (and no `code_location`). I think if `dependencies` is recognised as a python package, it is installed, so import statements work independently from the working directory. If not, it is an absolute import. And that absolute import is not possible in the inference container because the directory structure is different.

I believe your problem is the unpickling. Because when unpickling, the import of your custom module is attempted the same way it was available in the environment when you saved the model. And this does probably not work if your import is relative. So instead, put your dependencies in a folder and add an `__init__.py`, so it's a package and will be installed (you should see that it's being isntalled in the logs of the batch transform).

**Comment by WouterJTB** [comment]
> I had at some point the same problem which I don't recall in detail but I had a local `source_dir`, a folder instead of a file in `dependencies` and an `__init__.py` in dependencies (and no `code_location`). I think if `dependencies` is recognised as a python package, it is installed, so import statements work independently from the working directory. If not, it is an absolute import. And that absolute import is not possible in the inference container because the directory structure is different.
> 
> Hence, I believe your problem is the unpickling. Because when unpickling, the import of your custom module is attempted the same way it was available in the environment when you saved the model. And this does probably not work with your import. So instead, put your dependencies in a folder and add an `__init__.py`, so it's a package and will be installed (you should see that it's being isntalled in the logs of the batch transform).
> 
> Edit: Ah just found this answer on StackOverflow: https://stackoverflow.com/questions/56260720/import-custom-modules-in-amazon-sagemaker-jupyter-notebook.

Thanks! Was able to solve it with your help.

So what I did: 

- Replace the SKLearnProcessor in my pipeline with a FrameworkProcessor, so that I could add code dependencies to my processor.run() pipeline step, similar to how I could when instantiating my SKLearnModel.
- Then add the dependencies as folder/package and import them the same way in both the preprocessor and inference scripts.

Tbh, I think the key here was changing to a FrameworkProcessor which allowed for adding dependencies. I expect that adding a utils.py file would work just as well (looking at the logs, .py files also seem get installed as package on the transformer container), as long as the importing and referencing is the same in both the training/processing and the inference script.

I'll add a feature request to the sagemaker-python-sdk repo. As currently, it is not possible to add local dependencies to the SKLearnProcessor and SKLearnEstimator classes, so I would not be able to solve my issue using these classes.
