### ISSUE TITLE
When specifying a source_dir **AND** an entry_point that is not directly in the source_dir, the import fails. 

### ISSUE THREAD

**Issue by adurivault** [aws/sagemaker-scikit-learn-container#29]
I created a github repo to reproduce the problem. When I run the following code from a sagemaker notebook :
```
from sagemaker.sklearn import SKLearn
import sagemaker

git_config = {
    'repo': 'https://github.com/adurivault/aws-sagemaker-example.git',
    'branch': 'master',
}

skl_estimator = SKLearn(
    'src/main.py',
    train_instance_type="local",
    role=sagemaker.get_execution_role(),
    source_dir='sub-dir',
    git_config=git_config,
)

skl_estimator.fit({})
```

I get the following error :
```
Invoking script with the following command:

/miniconda3/bin/python -m src/main


/miniconda3/bin/python: No module named src/main
2019-11-28 11:05:22,748 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/miniconda3/bin/python -m src/main"
```

It seems to me that the correct command should be /miniconda3/bin/python -m src.main

Issue already reported here : https://github.com/aws/sagemaker-scikit-learn-container/pull/23#issuecomment-559450135

**Comment by ericangelokim** [comment]
Hello,

This is implemented in the [sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk) repository ; please see the pydocs [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1440)

**Comment by ericangelokim** [comment]
Hello,

This is implemented in the [sagemaker-python-sdk](https://github.com/aws/sagemaker-python-sdk) repository ; please see the pydocs [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1440)

**Comment by adurivault** [comment]
@ericangelokim I don't think what you pointed me to solves the issue I raised. 

As I explained here [here](https://github.com/aws/sagemaker-scikit-learn-container/pull/23#issuecomment-559450135) if I fill **both** `source_dir` **and** `entry_point`, with and `entry_point` that is is a subdirectory, then the program fails. Once again today I encountered this issue in a different context, but the underlying problem is the same.

**Comment by ericangelokim** [comment]
I see. I apologize, the implementation is actually written in the sagemaker-containers code here: https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_modules.py

Do you have more stacktrace you can point to? The relevant files seem to be:
* https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_trainer.py#L73
* https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/entry_point.py#L99
* https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_runner.py#L34
* https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_process.py#L134
