### ISSUE TITLE
Generate release

### ISSUE THREAD

**Issue by oblute** [aws/sagemaker-scikit-learn-container#32]
Is it possible to generate a release on github for version 1.0, as in the setup.py? Thanks!

**Comment by rluria14** [comment]
@laurenyu

**Comment by laurenyu** [comment]
@edwardjkim

**Comment by elangovana** [comment]
Hi Team,  please use the release feature on GitHub so we can tie the source code with the docker image version for debugging thanks

**Comment by mabunday** [comment]
Releases published: https://github.com/aws/sagemaker-scikit-learn-container/releases
