### ISSUE TITLE
How to package a model for deployment

### ISSUE THREAD

**Issue by cliveseldon** [aws/sagemaker-scikit-learn-container#4]
Its not clear how to package a model for deployment. The code seems to accept a tar.gz for the module code to be deployed from S3 but this doesn't set up the /opt/ml/model folder for the user to load the model via the model_fn.

For example: setting the env variable SAGEMAKER_SUBMIT_DIRECTORY="s3://my-s3-bucket/model.tar.gz"  works but only for the module code.

How can one supply the location of the saved scikit-learn model pickle created during training?

**Comment by ericaws** [comment]
Hello, this can be done more conveniently through the SKLearn predictors. Please see the documentation at sagemaker-python-sdk here:

https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/sklearn
