### ISSUE TITLE
Ability to return 4XX error from inference.py code

### ISSUE THREAD

**Issue by trams** [aws/sagemaker-scikit-learn-container#62]
https://sagemaker.readthedocs.io/en/stable/frameworks/sklearn/using_sklearn.html#serve-a-model

permit to customize the way we decode, encode and run predictions
In my use case I customize predict_fn as follows

    try:
        pred_prob = model.predict_proba(input_data)
    except ValueError as e:
        message = str(e)
        raise GenericInferenceToolkitError(status_code=400, message=message)
    return pred_prob

What I am trying to archive is to pass though an error I receive from predict_proba to the client but this does not work
Why do I want this? A typical error I experience is a wrong size of the input_data and now it results in the client getting 5xx error which is
1. conterproductive cause it is not internal server error but rather a problem with a request
2. leads to retries by my client (hey, it is 5xx and it is reasonable to try to retry)
3. Poor error messaging

Without looking at cloudwatch logs it is quite hard to establish the nature of the problem

What do I want?
A way to communicate the change in status_code and (ideally) a way to customize message.
When I found GenericInferenceToolkitError I was excited but doing github code grep shows it is not used anywhere

Please advise

**Comment by trams** [comment]
Actually I just found out that output_fn return flask Response object
so there is a way to customize an error message now

**Comment by tomekzbrozek** [comment]
@trams could you share an example of how you solved this (returning 4xx status code from inference.py, using flask response)? Thanks 🙇
