### ISSUE TITLE
Support for v0.24.1 of sklearn

### ISSUE THREAD

**Issue by nicmer** [aws/sagemaker-scikit-learn-container#67]
Version 0.24 supports some nice new features:
- https://scikit-learn.org/stable/auto_examples/release_highlights/plot_release_highlights_0_24_0.html

Would be great if sagemaker would support the new sklearn version.

**Comment by trams** [comment]
We are also very interested in using v0.24.1 with Sagemaker and we would love not to build a custom container for that
The reason we want to use v0.24.1 is OrdinalEncoder has handle_unknown flag (more here https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OrdinalEncoder.html)

**Comment by trams** [comment]
BTW, there is at least one fork which seemed to address the issue https://github.com/aws/sagemaker-scikit-learn-container/compare/master...tophatter:dh-v24

I would not necessarily merge it as is but it is a nice starting point

**Comment by mabunday** [comment]
Closing since 1.0 is now supported: https://github.com/aws/sagemaker-scikit-learn-container/releases/tag/v1.0-1
