### ISSUE TITLE
Confusion about scikit version 0.23-1

### ISSUE THREAD

**Issue by gerold-csendes-epam** [aws/sagemaker-scikit-learn-container#72]
I am little bit confused why `0.23-1` version identification is used in [code ](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/image_uri_config/sklearn.json#L35)and in the docs  when in fact the installed version is `0.23.2` as specified in the [Dockerfile](https://github.com/aws/sagemaker-scikit-learn-container/blob/master/docker/0.23-1/base/Dockerfile.cpu#L106)

Am I missing something or is this indeed an incosistency?

**Comment by dharris10-chwy** [comment]
I have the same question. Could we get some clarity from the maintainers?

**Comment by iyerr3** [comment]
The version number `0.23-1` contains two parts - scikit-learn version (`0.23`) and a SageMaker identifier (`-1`) that is used for major upgrades within the same sklearn version. We don't distinguish between minor versions within a release (i.e. no separate versions for `0.23.1` and `0.23.2`).

**Comment by gerold-csendes-epam** [comment]
got it, thanks @iyerr3
