### ISSUE TITLE
Update boto3 version to >= 1.17.74

### ISSUE THREAD

**Issue by bobbywlindsey** [aws/sagemaker-scikit-learn-container#80]
Update boto3 version in container from 1.16.4 to something >= 1.17.74 in order to support newer SageMaker client functions like `list_artifacts`.

**Comment by bobbywlindsey** [comment]
Created [this pull request](https://github.com/aws/sagemaker-scikit-learn-container/pull/123) to fix this issue. Awaiting approvals to be merged into the main branch.

**Comment by bobbywlindsey** [comment]
PR has been merged into main branch. Closing this issue.

**Comment by mabunday** [comment]
Which regions is this change needed in? I can give you two a ping once the change has been deployed to the associated ECR. In general, it takes around 7 working days for a full deployment to all production regions.

**Comment by bobbywlindsey** [comment]
@mabunday The change is needed in all regions but would be nice to prioritize us-east-1 and us-west-2.

**Comment by mabunday** [comment]
There was a bit of a delay due to the holidays, but the change should be in us-west-2 now and it will be deployed to us-east-1 on Monday, July 11. 

Thanks for raising this!
