### ISSUE TITLE
Invalid gpg signature for apt.kitware.com in  sagemaker-scikit-learn:0.23-1-cpu-py3

### ISSUE THREAD

**Issue by samir-souza** [aws/sagemaker-scikit-learn-container#87]
The latest version of sagemaker-scikit-learn:0.23-1-cpu-py3 introduced a signature failure. This failure breaks the applications that depend on new packages. When you run "apt update", apt doesn't find the correct pubkey for apt.kitware.com and fails.

**LOGS**
root@1b240212ef9b:/# apt updateGet:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]Get:2 https://apt.kitware.com/ubuntu bionic InRelease [11.0 kB]Get:3 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]Get:4 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1426 kB]Err:2 https://apt.kitware.com/ubuntu bionic InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE19EB17684BA42DGet:5 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [543 kB]Get:6 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [26.7 kB]Get:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2295 kB]Get:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]Get:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2200 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2731 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [34.4 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [575 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
Reading package lists... Done
W: GPG error: https://apt.kitware.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DE19EB17684BA42D
E: The repository 'https://apt.kitware.com/ubuntu bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**WORKAROUND**
Workaround:
$ wget https://raw.githubusercontent.com/tommybutler/apt-key-install/master/apt-key-install
$ chmod +x apt-key-install
$ ./apt-key-install DE19EB17684BA42D https://apt.kitware.com/keys/kitware-archive-latest.asc
$ apt update

**SOLUTION**
Follow the instructions in this page: https://apt.kitware.com/ and install the correct keys in docker image

**Comment by jpvandervelden** [comment]
I'm having the same issue.

**Comment by mabunday** [comment]
Should be fixed by https://github.com/aws/sagemaker-scikit-learn-container/commit/76068a3f70c486ecf26d3694d15bf7ffa19b05a1 but please re-open if still having trouble.
