### ISSUE TITLE
scikit-learn 1.0.1

### ISSUE THREAD

**Issue by marcoracer** [aws/sagemaker-scikit-learn-container#95]
Version 1.0.1 supports some nice new features:

https://scikit-learn.org/stable/auto_examples/release_highlights/plot_release_highlights_1_0_0.html

Would be great if sagemaker would support the new sklearn version.

**Comment by SuperBo** [comment]
one vote for this. please update to newer version

**Comment by trams** [comment]
Here is also a related ticket (with attached pull request) to update scikit-learn version to something newer https://github.com/aws/sagemaker-scikit-learn-container/issues/67

**Comment by lorenzwalthert** [comment]
I think that's closed with #107. Thanks 🥳

**Comment by marcoracer** [comment]
Sure, tnks @lorenzwalthert
